### ISSUE TITLE
Error when compile the model using tensorflow_backend

### ISSUE THREAD

**Issue by lelechen63** [jackfan00/VGG#2]
Hi,

I try to follow your work, but when I start to train on batch, it shows:

Traceback (most recent call last):
  File "main.py", line 74, in <module>
    model.compile(optimizer=sgd, loss=detregionloss.regionloss, metrics=[detregionloss.regionmetrics])
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.4-py2.7.egg/keras/models.py", line 786, in compile
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.4-py2.7.egg/keras/engine/training.py", line 968, in compile
    metric_result = masked_metric_fn(y_true, y_pred, mask=masks[i])
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.4-py2.7.egg/keras/engine/training.py", line 495, in masked
    return K.mean(score_array)
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.4-py2.7.egg/keras/backend/tensorflow_backend.py", line 1254, in mean
    axis = _normalize_axis(axis, ndim(x))
  File "/usr/local/lib/python2.7/dist-packages/Keras-2.0.4-py2.7.egg/keras/backend/tensorflow_backend.py", line 479, in ndim
    dims = x.get_shape()._dims
AttributeError: 'dict' object has no attribute 'get_shape'

**Comment by jackfan00** [comment]
please git clone again , and use main_bnum.py instead , and I update readme file, please check it again
